### PR TITLE
Add Region as a configuration parameter

### PR DESCRIPTION
**Pull request by ghost**
Added a configuration parameter for region.  It defaults to LON which is what the original hardcoded version was.  Added a parameter to the rackspaceAPI classes constructor to pass the region into the class, and passed the parameters in through the service container.  There was an existing brake in the the test suit that still needs to get looked into.

### CODE REVIEW

**Comment by liuggio** [comment]
:+1:

**Comment by lmammino** [comment]
Should be pushed also to the default packagist repository (https://github.com/tvision/RackspaceCloudFilesBundle) to enable the updates even for those who use composer...

**Comment by liuggio** [comment]
Luciano, the Tvision group improved this bundle and I moved the maintaince to tvision crew.

You could get the repo from there.
Let me know if you have problem

**Comment by lmammino** [comment]
Thanks @liuggio!
I just wanted to say that the tvision repo is not fully aligned with this one. It misses the ability to provide configuration for the "region" attribute.
Should I open a issue on that repo?

**Comment by ghost** [comment]
Could have them pull the current version from here...

**Comment by lmammino** [comment]
Issues are not enabled in that repo...

**Comment by liuggio** [comment]
Sorry guys on Thu. everything will be shiny new on the tvision repo.

Really sorry for this.
cc  @toretto460

**Pull request merged**
