### PR TITLE
Added a rscf:assets:install command to install assets directly to rackspace cloudfiles

### PR DESCRIPTION
**Pull request by benjamindulau**
Like the title says ;-)

Usage:

```
app/console rscf:assets:install rscf://container_name/virtual_path --verbose
```

Bye

### CODE REVIEW

**Comment by liuggio** [comment]
This looks good, but sorry I didn't get the point, 
we currently use this bundle with assetic:dump, which are the advantages of having a command?

**Comment by benjamindulau** [comment]
This command is the equivalent of the default "assets:install" one in framework bundle, which copies files from all Resources/public bundles directories into web/ dir by default. 

This is not related to assetic which only handles css and js files. Note that assetic is not necessary used in every project. 

So the command dumps these files directly to the cloudfiles container by using the stream wrapper. 

This is obviously not needed when using assetic with the cssembed filter. But when it is not used, we still need to send images to cloudfiles. BTW maybe i could add an option to ignore css and js files when assetic is used.

**Comment by liuggio** [comment]
:+1:

**Comment by liuggio** [comment]
please could you add some documentation on the readme?

**Pull request merged**
